name: Build roomy-chats Backend and Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Build Spring Boot Backend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: chat-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      

      - name: Build Spring Boot app
        run: mvn clean package -DskipTests
        
  frontend:
    name: Build React Frontend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: front-chat

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build
